# 1.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# load in datasets
listings = pd.read_csv('listings.csv')
reviews = pd.read_csv('reviews.csv')
neighborhoods = pd.read_csv('neighborhoods.csv')

### listings info

In [8]:
listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 5824 entries, 0 to 5823
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              5824 non-null   int64
 1   name                            5824 non-null   str
 2   host_id                         5824 non-null   int64
 3   host_name                       5814 non-null   str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   5824 non-null   str
 6   latitude                        5824 non-null   float64
 7   longitude                       5824 non-null   float64
 8   room_type                       5824 non-null   str
 9   price                           5298 non-null   float64
 10  minimum_nights                  5824 non-null   int64
 11  number_of_reviews               5824 non-null   int64
 12  last_review                     5025 non-null   str
 13  reviews_per_month               5025 non-null   float64
 14  calculated_host_listings_count  5824 non-null   int64
 15  availability_365                5824 non-null   int64
 16  number_of_reviews_ltm           5824 non-null   int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), str(5)
memory usage: 819.1 KB

In [9]:
# first few rows of the listings dataset
listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,61878,MODERN LIVING AND FURNISHINGS,300211,Rita,NaN,District 2,32.81690,-96.82018,Entire home/apt,72.0,30,57,2025-04-30,0.31,1,333,2,NaN
1,795703,Amazing location walk to Downtown Dallas,4191322,Michelle,NaN,District 14,32.80327,-96.80976,Entire home/apt,299.0,30,71,2024-07-27,0.46,1,270,0,NaN
2,1277933,The Santa Fe Suite and Maxfield Parrish Suite,6904484,C. F. Sandy,NaN,District 11,32.92449,-96.79062,Private room,56.0,1,30,2019-11-09,0.29,1,326,0,NaN
3,1479800,SMU/Trendy Greenville/with Private Bath,3809024,Holly,NaN,District 14,32.83103,-96.76380,Private room,131.0,2,103,2025-10-26,0.69,3,136,1,NaN
4,1507428,"4323 McKinney Ave studio 8, WIFI, Parking",6063232,Joan,NaN,District 14,32.81961,-96.78996,Entire home/apt,45.0,30,74,2025-05-19,0.50,6,332,1,NaN

In [7]:
reviews.head()

   listing_id        date
0       61878  2010-12-29
1       61878  2011-01-03
2       61878  2011-02-13
3       61878  2011-02-17
4       61878  2011-02-23