# Dallas Air Bnb Analysis

In [1]:
# create your virtual environment

# activate the virtual environment
# install the dependencies from requirements.txt'
 
# pip install -r requirements.txt # put this in terminal to install the dependencies!!!
 
# run the application

**Table of contents**<a id='toc0_'></a>    
- [](#toc1_)    
    - [listings info](#toc1_1_1_)    
    - [reviews info](#toc1_1_2_)    
    - [neighborhoods info](#toc1_1_3_)    
    - [calendar info](#toc1_1_4_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [ ]:
# load in datasets
listings = pd.read_csv('listings.csv')
reviews = pd.read_csv('reviews.csv')
neighborhoods = pd.read_csv('neighborhoods.csv')
calendar = pd.read_csv('calendar.csv.gz',compression='gzip')

### <a id='toc1_1_1_'></a>[listings info](#toc0_)

In [8]:
listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 5824 entries, 0 to 5823
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              5824 non-null   int64
 1   name                            5824 non-null   str
 2   host_id                         5824 non-null   int64
 3   host_name                       5814 non-null   str
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   5824 non-null   str
 6   latitude                        5824 non-null   float64
 7   longitude                       5824 non-null   float64
 8   room_type                       5824 non-null   str
 9   price                           5298 non-null   float64
 10  minimum_nights                  5824 non-null   int64
 11  number_of_reviews               5824 non-null   int64
 12  last_review                     5025 non-null   str
 13  reviews_per_month               5025 non-null   float64
 14  calculated_host_listings_count  5824 non-null   int64
 15  availability_365                5824 non-null   int64
 16  number_of_reviews_ltm           5824 non-null   int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), str(5)
memory usage: 819.1 KB

In [18]:
listings.describe()

,id,host_id,neighbourhood_group,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,5.824000e+03,5.824000e+03,0.0,5824.000000,5824.000000,5298.000000,5824.000000,5824.000000,5025.000000,5824.000000,5824.000000,5824.000000,0.0
mean,9.355043e+17,2.958762e+08,NaN,32.808114,-96.795081,338.651378,8.187500,43.300309,2.006687,12.731799,250.256181,13.608001,NaN
std,5.563757e+17,2.262178e+08,NaN,0.063345,0.047159,2354.403581,20.040193,85.304759,1.953354,22.947420,121.993453,19.567363,NaN
min,6.187800e+04,4.342200e+04,NaN,32.633790,-96.992697,12.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000,NaN
25%,6.267476e+17,7.467975e+07,NaN,32.776285,-96.824557,86.000000,1.000000,3.000000,0.510000,1.000000,163.750000,1.000000,NaN
50%,1.138499e+18,2.647479e+08,NaN,32.799656,-96.795630,127.000000,2.000000,14.000000,1.430000,4.000000,305.000000,6.000000,NaN
75%,1.408393e+18,4.875575e+08,NaN,32.822631,-96.770981,225.000000,3.000000,46.000000,2.970000,12.000000,354.000000,20.000000,NaN
max,1.559970e+18,7.304258e+08,NaN,33.015150,-96.481240,50000.000000,365.000000,1406.000000,28.820000,114.000000,365.000000,431.000000,NaN

In [9]:
# first few rows of the listings dataset
listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,61878,MODERN LIVING AND FURNISHINGS,300211,Rita,NaN,District 2,32.81690,-96.82018,Entire home/apt,72.0,30,57,2025-04-30,0.31,1,333,2,NaN
1,795703,Amazing location walk to Downtown Dallas,4191322,Michelle,NaN,District 14,32.80327,-96.80976,Entire home/apt,299.0,30,71,2024-07-27,0.46,1,270,0,NaN
2,1277933,The Santa Fe Suite and Maxfield Parrish Suite,6904484,C. F. Sandy,NaN,District 11,32.92449,-96.79062,Private room,56.0,1,30,2019-11-09,0.29,1,326,0,NaN
3,1479800,SMU/Trendy Greenville/with Private Bath,3809024,Holly,NaN,District 14,32.83103,-96.76380,Private room,131.0,2,103,2025-10-26,0.69,3,136,1,NaN
4,1507428,"4323 McKinney Ave studio 8, WIFI, Parking",6063232,Joan,NaN,District 14,32.81961,-96.78996,Entire home/apt,45.0,30,74,2025-05-19,0.50,6,332,1,NaN

### <a id='toc1_1_2_'></a>[reviews info](#toc0_)

In [11]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 252181 entries, 0 to 252180
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   listing_id  252181 non-null  int64
 1   date        252181 non-null  str
dtypes: int64(1), str(1)
memory usage: 3.8 MB

In [17]:
reviews.describe()

         listing_id
count  2.521810e+05
mean   4.812801e+17
std    5.346157e+17
min    6.187800e+04
25%    3.428229e+07
50%    5.347852e+07
75%    9.631242e+17
max    1.559708e+18

In [7]:
reviews.head()

   listing_id        date
0       61878  2010-12-29
1       61878  2011-01-03
2       61878  2011-02-13
3       61878  2011-02-17
4       61878  2011-02-23

### <a id='toc1_1_3_'></a>[neighborhoods info](#toc0_)

In [19]:
neighborhoods.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  0 non-null      float64
 1   neighbourhood        14 non-null     str
dtypes: float64(1), str(1)
memory usage: 356.0 bytes

In [20]:
neighborhoods.describe()

       neighbourhood_group
count                  0.0
mean                   NaN
std                    NaN
min                    NaN
25%                    NaN
50%                    NaN
75%                    NaN
max                    NaN

In [21]:
neighborhoods.head()

   neighbourhood_group neighbourhood
0                  NaN    District 1
1                  NaN   District 10
2                  NaN   District 11
3                  NaN   District 12
4                  NaN   District 13

### <a id='toc1_1_4_'></a>[calendar info](#toc0_)

In [14]:
print(calendar.info())

<class 'pandas.DataFrame'>
RangeIndex: 2125773 entries, 0 to 2125772
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            str
 2   available       str
 3   price           float64
 4   adjusted_price  float64
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: float64(2), int64(3), str(2)
memory usage: 113.5 MB
None

In [16]:
calendar.describe()

         listing_id  price  adjusted_price  minimum_nights  maximum_nights
count  2.125773e+06    0.0             0.0    2.125773e+06    2.125773e+06
mean   9.355057e+17    NaN             NaN    8.897847e+00    2.581736e+06
std    5.563276e+17    NaN             NaN    2.051487e+01    7.440561e+07
min    6.187800e+04    NaN             NaN    1.000000e+00    1.000000e+00
25%    6.268488e+17    NaN             NaN    1.000000e+00    3.650000e+02
50%    1.138504e+18    NaN             NaN    2.000000e+00    3.650000e+02
75%    1.408680e+18    NaN             NaN    5.000000e+00    1.125000e+03
max    1.559970e+18    NaN             NaN    3.650000e+02    2.147484e+09